export const CardType = {
  ATTACK: 'ATTACK',
  HEAL: 'HEAL',
  HYBRID: 'HYBRID',
  SPECIAL: 'SPECIAL',
  CHAOS: 'CHAOS'
};

export const EffectType = {
  DAMAGE: 'DAMAGE',
  HEAL: 'HEAL',
  FULL_HEAL: 'FULL_HEAL',
  REFLECT: 'REFLECT',
  SWAP_HEALTH: 'SWAP_HEALTH',
  DRAIN: 'DRAIN',
  IMMUNITY: 'IMMUNITY',
  JUDGMENT: 'JUDGMENT',
  MULTI_TARGET: 'MULTI_TARGET',
  MASS_DAMAGE: 'MASS_DAMAGE',
  MASS_HEAL: 'MASS_HEAL',
  DRAW: 'DRAW',
  DISCARD: 'DISCARD',
  SELF_DAMAGE: 'SELF_DAMAGE',
  ALLY_HEAL: 'ALLY_HEAL',
  DISABLE_HEALING: 'DISABLE_HEALING',
  DISABLE_ALL_HEALING: 'DISABLE_ALL_HEALING',
  WEAKEN: 'WEAKEN',
  BOOST_NEXT: 'BOOST_NEXT',
  EXTRA_TURN: 'EXTRA_TURN',
  SKIP_TURN: 'SKIP_TURN'
};

export const Rarity = {
  COMMON: 'common',
  UNCOMMON: 'uncommon',
  RARE: 'rare'
};